# Generated by Django 4.2.30 on 2026-04-30 23:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seaport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='landshipment',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='maritimeshipment',
            name='container_number',
        ),
        migrations.RemoveField(
            model_name='maritimeshipment',
            name='port_of_arrival',
        ),
        migrations.RemoveField(
            model_name='maritimeshipment',
            name='port_of_departure',
        ),
        migrations.RemoveField(
            model_name='maritimeshipment',
            name='vessel_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='origin',
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maritimeshipment',
            name='fleet_number',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]{3}\\d{4}[A-Za-z]{1}$', 'Fleet number must be 3 letters, 4 numbers, 1 letter (e.g. AAA1234A).')]),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='logistics.product'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='product_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shipment',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{10}$', 'Tracking number must be exactly 10 alphanumeric characters.')]),
        ),
        migrations.AlterField(
            model_name='landshipment',
            name='vehicle_plate',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]{3}\\d{3}$', 'Plate must be 3 letters followed by 3 numbers (e.g. AAA123).')]),
        ),
        migrations.AddField(
            model_name='landshipment',
            name='delivery_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='land_shipments', to='logistics.warehouse'),
        ),
        migrations.AddField(
            model_name='maritimeshipment',
            name='delivery_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maritime_shipments', to='logistics.seaport'),
        ),
    ]
