# Generated by Django 4.2.30 on 2026-05-01 00:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_seaport_warehouse_remove_landshipment_driver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
