# Generated by Django 4.2.30 on 2026-05-01 00:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_shipment_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='product_quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
