# Generated by Django 4.2.30 on 2026-05-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_shipment_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
