# Generated by Django 4.2.30 on 2026-05-03 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_client_is_active_seaport_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landshipment',
            name='vehicle_plate',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]{3}\\d{3}$', 'La placa del vehículo debe tener 3 letras seguidas de 3 números (ej. AAA123).')]),
        ),
        migrations.AlterField(
            model_name='maritimeshipment',
            name='fleet_number',
            field=models.CharField(default='DEFAULT1', max_length=8, validators=[django.core.validators.RegexValidator('^[A-Za-z]{3}\\d{4}[A-Za-z]{1}$', 'El número de flota debe tener 3 letras, 4 números y 1 letra (ej. AAA1234A).')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(default='TRACK00001', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{10}$', 'El número de seguimiento debe tener 10 caracteres alfanuméricos.')]),
            preserve_default=False,
        ),
    ]
